name: Docker Deploy

on:
    push:
      branches: [ main, docker-deployment ]
    release:
      types: [published]
    workflow_dispatch:
      inputs:
        example_input:
          description: 'Manuall trigger for workflow'
          required: false
          default: 'default_value'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yourusername/yourrepository:latest